---
- name: create new ansible user
  user:
    name: "{{ ansible_orchestration_user }}"
    state: present
    groups: sudo
    shell: /bin/bash
    append: yes

- name: enable passwordless sudo for ansible user
  template:
    src: ansible.sudoers
    dest: "/etc/sudoers.d/{{ ansible_orchestration_user }}"
    owner: root
    group: root
    mode: 0600

- debug:
    var: "hostvars[item]['orchestrationkey']"
    verbosity: 1
  with_items: "{{ groups['ansible-master'] }}"

- name: deploy new ansible master ssh key
  authorized_key:
    exclusive: yes
    key: "{{ hostvars[item]['orchestrationkey'] }}"
    user: "{{ ansible_orchestration_user }}"
    state: present
    manage_dir: yes
  with_items: "{{ groups['ansible-master'] }}"
